spring:
#  rabbitmq:
#    #    host: rabbimq-compose.onrender.com
#    host: localhost
#    port: 5672
#    username: admin
#    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.postgresql.Driver
    username: taskmanagerdb_ufh1_user
    password: FzyhwYD7P9FBlrEoe5qjKej5k4DEsZRL
    url: jdbc:postgresql://dpg-d2icetmuk2gs73de73ug-a.oregon-postgres.render.com/taskmanagerdb_ufh1
    platform: postgres
    initialization-mode: always
    continue-on-error: true
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    database: postgresql
